version: '3.8'

services:
  picshare_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    build:
      context: ./project/src/config/db
      dockerfile: Dockerfile
    ports:
      - "5431:5432"

  picshare_web:
    build: ./project
    command: uvicorn project.src.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/posts/project
    ports:
      - "8004:8000"
    healthcheck:
      test: curl --fail http://localhost:8000/docs || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
    environment:
      ENVIRONMENT: dev
      TESTING: 0
      DATABASE_URL: postgresql://${POSTGRES_USER}@picshare_db:5432/${POSTGRES_DATABASE_MAIN}
      DATABASE_TEST_URL: postgresql://${POSTGRES_USER}@picshare_db:5432/${POSTGRES_DATABASE_TEST}
    depends_on:
      - picshare_db