version: '3.8'

services:
  picshare_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER_NAME}
      POSTGRES_PASSWORD: ${DATABASE_USER_PASSWORD}
    build:
      context: ./project/src/config/db
      dockerfile: Dockerfile
    expose:
      - 5432

  picshare_web:
    build: ./project
    command: uvicorn src.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      ENVIRONMENT: dev
      TESTING: 0
      DATABASE_URL: postgresql://${DATABASE_USER_NAME}:${DATABASE_USER_PASSWORD}@picshare_db:5432/${DATABASE_NAME}
      DATABASE_TEST_URL: postgresql://${DATABASE_USER_NAME}:${DATABASE_USER_PASSWORD}@picshare_db:5432/${TEST_DATABASE_NAME}
    depends_on:
      - picshare_db